[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "cookiebaker"
version = "0.1.0"
dependencies = ["PySide6>=6.8.0"]

[project.scripts]
cb_authenticate = "cookiebaker.entrypoint.cb:main"
cb_to_curl = "cookiebaker.entrypoint.cb_to_curl:main"

[tool.setuptools.packages.find]
where = ["src"]
