[build-system]
requires = ["setuptools>=61.0", "wheel>=0.43.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cookietruck"
version = "0.1.1"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["PySide6>=6.8.0"]

[project.urls]
Homepage = "https://github.com/dsoprea/cookietruck"

[project.optional-dependencies]
test = ["pytest>=8.0"]
dev = ["build>=1.0.0", "twine>=6.0.0"]

[project.scripts]
ct_authenticate = "cookietruck.entrypoint.ct_authenticate:main"
ct_to_curl = "cookietruck.entrypoint.ct_to_curl:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
