"""Cookie normalization, capture helpers, and session JSON payload (non-CLI)."""

# Standard library

import datetime
import logging
import typing

# Qt (PySide6)

import PySide6.QtCore
import PySide6.QtNetwork
import PySide6.QtWebEngineCore

_LOGGER = logging.getLogger(__name__)

_CURL_COOKIEJAR_HEADER = \
    "# Netscape HTTP Cookie File\n" \
    "# https://curl.se/docs/http-cookies.html\n" \
    "# This file was generated by cookietruck! Edit at your own risk.\n" \
    "\n"


def as_bytes(x: object) -> bytes:
    """Coerce ``x`` to ``bytes``: UTF-8 for ``str``, otherwise ``bytes(...)``."""

    if isinstance(x, str):
        return x.encode("utf-8", errors="replace")
    return bytes(x)


def normalize_url(text: str) -> PySide6.QtCore.QUrl:
    """Turn user input into an absolute ``QUrl``, defaulting scheme to ``https``."""

    text = text.strip()

    # Empty input yields an invalid URL so callers can reject early.

    if not text:
        return PySide6.QtCore.QUrl()

    # Bare hostnames become navigable URLs once a scheme is assumed.

    if "://" not in text:
        text = "https://" + text
    return PySide6.QtCore.QUrl.fromUserInput(text)


def cookie_key(c: PySide6.QtNetwork.QNetworkCookie) -> typing.Tuple[bytes, bytes, bytes]:
    """Stable dict key for deduplicating cookies: ``(name, domain, path)`` as bytes."""

    domain = c.domain()
    path = c.path() or "/"
    return (as_bytes(c.name()), as_bytes(domain), as_bytes(path))


def same_site_name(c: PySide6.QtNetwork.QNetworkCookie) -> str | None:
    """Map Qt same-site policy to JSON string values; ``None`` omits the field."""

    policy = c.sameSitePolicy()
    if policy == PySide6.QtNetwork.QNetworkCookie.SameSite.Default:
        return None
    if policy == PySide6.QtNetwork.QNetworkCookie.SameSite.None_:
        return "None"
    if policy == PySide6.QtNetwork.QNetworkCookie.SameSite.Lax:
        return "Lax"
    if policy == PySide6.QtNetwork.QNetworkCookie.SameSite.Strict:
        return "Strict"

    # Fallback for unexpected enum values—keeps export robust.

    return str(int(policy))


def cookies_as_records(cookies: typing.Iterable[PySide6.QtNetwork.QNetworkCookie]) -> typing.List[dict]:
    """Serialize cookies to sorted JSON-friendly dict rows (name, domain, flags, etc.)."""

    rows: typing.List[dict] = []
    for c in cookies:
        exp = c.expirationDate()

        # Core attributes always emitted for HTTP tooling / export consumers.

        row = {
            "name": as_bytes(c.name()).decode("utf-8", errors="replace"),
            "value": as_bytes(c.value()).decode("utf-8", errors="replace"),
            "domain": (c.domain() or "").strip(),
            "path": c.path() or "/",
            "secure": bool(c.isSecure()),
            "httpOnly": bool(c.isHttpOnly()),
        }
        ss = same_site_name(c)
        if ss is not None:
            row["sameSite"] = ss
        if exp.isValid():
            row["expires"] = exp.toString(PySide6.QtCore.Qt.DateFormat.ISODateWithMs)
        rows.append(row)

    # Deterministic ordering helps diffing and human inspection.

    rows.sort(key=lambda r: (r["domain"], r["path"], r["name"]))
    return rows


def _cookie_field_is_binary_for_cookiejar(raw: bytes) -> bool:
    """Return True when ``raw`` cannot be represented as plain Netscape cookiejar text."""

    if b"\t" in raw or b"\n" in raw or b"\r" in raw or b"\x00" in raw:
        return True

    try:
        raw.decode("utf-8")
    except UnicodeDecodeError:
        return True

    return False


def _decode_cookie_field_for_cookiejar(raw: bytes) -> str:
    """Decode a cookie name or value for Netscape cookiejar export."""

    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return raw.decode("latin-1")


def _cookiejar_sort_key(c: PySide6.QtNetwork.QNetworkCookie) -> typing.Tuple[str, str, str]:
    """Sort key aligned with ``cookies_as_records`` ordering."""

    name = as_bytes(c.name()).decode("utf-8", errors="replace")
    return ((c.domain() or "").strip(), c.path() or "/", name)


def are_cookies_binary_for_cookiejar(
    cookies: typing.Iterable[PySide6.QtNetwork.QNetworkCookie],
) -> bool:
    """Return True when any cookie name or value is unsafe for a TTY cookiejar dump."""

    for c in cookies:
        name_bytes = as_bytes(c.name())
        value_bytes = as_bytes(c.value())

        if _cookie_field_is_binary_for_cookiejar(name_bytes):
            return True

        if _cookie_field_is_binary_for_cookiejar(value_bytes):
            return True

    return False


def is_binary_cookiejar_payload(payload: bytes) -> bool:
    """Return True when serialized cookiejar bytes are not safe UTF-8 text for a TTY."""

    if b"\x00" in payload:
        return True

    try:
        payload.decode("utf-8")
    except UnicodeDecodeError:
        return True

    return False


def build_curl_cookiejar(
    cookies: typing.Iterable[PySide6.QtNetwork.QNetworkCookie],
) -> bytes:
    """Serialize cookies to libcurl Netscape cookiejar bytes."""

    sorted_cookies = sorted(cookies, key=_cookiejar_sort_key)
    lines: typing.List[str] = [_CURL_COOKIEJAR_HEADER]

    for c in sorted_cookies:
        raw_domain = (c.domain() or "").strip()
        domain = raw_domain

        if c.isHttpOnly():
            domain = "#HttpOnly_{domain}".format(domain=raw_domain)

        if raw_domain.startswith("."):
            include_subdomains = "TRUE"
        else:
            include_subdomains = "FALSE"

        path = c.path() or "/"

        if c.isSecure():
            secure = "TRUE"
        else:
            secure = "FALSE"

        expiration = c.expirationDate()

        if expiration.isValid():
            expiry = str(int(expiration.toSecsSinceEpoch()))
        else:
            expiry = "0"

        name_bytes = as_bytes(c.name())
        value_bytes = as_bytes(c.value())
        name = _decode_cookie_field_for_cookiejar(name_bytes)
        value = _decode_cookie_field_for_cookiejar(value_bytes)
        line = "\t".join([
            domain,
            include_subdomains,
            path,
            secure,
            expiry,
            name,
            value,
        ])
        lines.append(line + "\n")

    text = "".join(lines)

    return text.encode("utf-8")


def _domain_matches(host: str, cookie_domain: str) -> bool:
    """Return True if ``host`` is covered by ``cookie_domain`` (with leading-dot rule)."""

    host = host.lower()
    cd = cookie_domain.lstrip(".").lower()
    return host == cd or host.endswith("." + cd)


def _path_matches(request_path: str, cookie_path: str) -> bool:
    """RFC-style path matching: prefix match with boundary at ``/``."""

    if not request_path.startswith("/"):
        request_path = "/" + request_path
    cp = cookie_path or "/"

    # Root-path cookies apply everywhere on the host.

    if cp == "/":
        return True
    if not request_path.startswith(cp):
        return False
    if len(request_path) == len(cp):
        return True

    # Require ``/`` after the cookie path prefix so ``/foo`` does not match ``/food``.

    return request_path[len(cp)] == "/"


def cookie_header_for_url(
    cookies: typing.Iterable[PySide6.QtNetwork.QNetworkCookie],
    url: PySide6.QtCore.QUrl,
) -> str:
    """Build a ``Cookie`` header value for ``url`` from in-memory cookies (browser-style filter)."""

    host = url.host()

    # Path-only matching: query is not part of the cookie ``Path`` attribute (RFC 6265).

    path = url.path() or "/"
    parts: typing.List[str] = []
    for c in cookies:
        dom = (c.domain() or "").strip()

        # Skip cookies that do not apply to this host/path.

        if not dom or not _domain_matches(host, dom):
            continue
        if not _path_matches(path, c.path() or "/"):
            continue

        # Secure cookies must not be sent on plain HTTP.

        if c.isSecure() and url.scheme().lower() != "https":
            continue
        name = as_bytes(c.name()).decode("utf-8", errors="replace")
        value = as_bytes(c.value()).decode("utf-8", errors="replace")
        parts.append(f"{name}={value}")
    return "; ".join(parts)


def settle_then_collect(
    cookie_map: typing.Dict[typing.Tuple[bytes, bytes, bytes], PySide6.QtNetwork.QNetworkCookie],
    settle_ms: int,
) -> typing.List[PySide6.QtNetwork.QNetworkCookie]:
    """Wait ``settle_ms`` so async cookie ops can finish, then return the in-memory cookie list."""

    _LOGGER.debug("cookie settle %d ms before collect", settle_ms)

    # Block the GUI thread briefly so async cookie ops can finish.

    loop = PySide6.QtCore.QEventLoop()
    PySide6.QtCore.QTimer.singleShot(settle_ms, loop.quit)
    loop.exec()
    cookies = list(cookie_map.values())
    _LOGGER.debug("collected %d QNetworkCookie instances", len(cookies))

    return cookies


def build_payload(base_url: str, cookies: typing.List[PySide6.QtNetwork.QNetworkCookie]) -> dict:
    """Assemble the session JSON object (schema: base_url, cookie_header, cookies, …)."""

    qurl = PySide6.QtCore.QUrl(base_url)
    return {
        "schema_version": 1,
        "base_url": base_url,
        "captured_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "cookie_header": cookie_header_for_url(cookies, qurl),
        "cookies": cookies_as_records(cookies),
    }
